/**
 * Loads the offline reference data (function docs + cookbook recipes) for the
 * MCP tools. The JSON is generated by scripts/genMcpResources.mjs into the
 * desktop's src-tauri/resources/mcp/ and copied into the .vsix by
 * scripts/bundle-resources.mjs — so the bundled path is tried first, with a dev
 * fallback to the sibling desktop repo (mirrors dwHost's jar resolution).
 */
import * as fs from 'fs';
import * as path from 'path';

const cache = new Map<string, unknown>();

export function loadMcpJson(extensionRoot: string, file: string): unknown {
  const cached = cache.get(file);
  if (cached !== undefined) return cached;
  const candidates = [
    path.join(extensionRoot, 'resources', 'mcp', file),
    path.join(extensionRoot, '..', 'src-tauri', 'resources', 'mcp', file),
  ];
  for (const c of candidates) {
    if (fs.existsSync(c)) {
      const data = JSON.parse(fs.readFileSync(c, 'utf8'));
      cache.set(file, data);
      return data;
    }
  }
  throw new Error(`MCP resource '${file}' not found. Looked in:\n${candidates.join('\n')}`);
}
